name: Release-Package ðŸŽ³

on:
  workflow_call:
    inputs:
      dry_run:
        required: true
        type: boolean
    secrets:
      transifex_token: 
        required: true

jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Fetch yapt
        run: |
          curl ${{ vars.YAPT_REPOSITORY_URL }} | tar -xzf -

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          architecture: x64
          cache: "pip"
          cache-dependency-path: "requirements/packaging.txt"      

      - name: Install Qt tranlation tools
        run: |
            sudo apt-get -qq update
            sudo apt-get -qq install qttools5-dev-tools pyqt5-dev-tools
            pip install --quiet -r requirements/packaging.txt

      - name: Pull transifex translations
        run: >
          qt-transifex -vv pull --compile
          --transifex-token "${{ secrets.transifex_token }}"

      - name: Fetch current changelog
        run: |
          ./yapt-pkg changelog >> release.md
          cat release.md

      - name: Package and deploy the zip
        env:
            DRY_RUN_OPT: ${{ inputs.dry_run == true && '--dry-run' || '' }}
        run: >
          ./yapt -v package --publish ${{ env.DRY_RUN_OPT }}
          --osgeo-username "${{ secrets.OSGEO_USERNAME }}"
          --osgeo-password "${{ secrets.OSGEO_PASSWORD }}"

      - name: Create release on GitHub
        if: ${{ inputs.dry_run == false }}
        uses: ncipollo/release-action@v1.20.0
        with:
          bodyFile: release.md
          artifacts: "*.zip"
          token: ${{ secrets.BOT_HUB_TOKEN }}

